//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsHisoryBuy = new HashSet<ProductsHisoryBuy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Haracteristics { get; set; }
        public string Description { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Wight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public string Photo { get; set; }
        public Nullable<int> OtherPhotoId { get; set; }
        public Nullable<bool> IsActual { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual OtherPhotos OtherPhotos { get; set; }
        public virtual ProductsCategories ProductsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsHisoryBuy> ProductsHisoryBuy { get; set; }
    }
}
