//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Windows.Media.Imaging;

    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.CustomerVisits = new HashSet<CustomerVisits>();
            this.HistiryBuy = new HashSet<HistiryBuy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string Photo { get; set; }
        public Nullable<int> OtherPhotoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerVisits> CustomerVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistiryBuy> HistiryBuy { get; set; }
        public virtual OtherPhotos OtherPhotos { get; set; }

        [NotMapped]
        public BitmapImage PhotoFromResources => !string.IsNullOrEmpty(Photo) ? new BitmapImage(new Uri("C:/Users/79393/source/repos/Learn/Photos/" + Photo)) : new BitmapImage(new Uri("C:/Users/79393/source/repos/Learn/Photos/school_logo.png"));

        [NotMapped]
        public string CostInfo => Sale.HasValue? (Cost - (Cost * Sale / 100))  + " рублей за " + Minutes + "минут" : Cost + " рублей за " + Minutes + "минут";

        [NotMapped]
        public string SaleInfo => Sale.HasValue? "* скидка" + Sale + "%" : "";
    }
}
